plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {

    // IntelliJ included when creating project
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'


    implementation group: 'org.mockito', name: 'mockito-core', version: '5.16.1'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.7.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    // JUnit 5 dependencies
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'  // Latest JUnit 5 API
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.2'  // JUnit 5 Engine for running tests

    // Mockito JUnit 5 extension
    testImplementation 'org.mockito:mockito-junit-jupiter:5.16.1'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'

}

test {
    useJUnitPlatform()
}